name: Release

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*.*.*"
    paths:
      - "installer.nsi"
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: Build for windows
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install NSIS
        uses: negrutiu/nsis-install@v2
        with:
          distro: official
          arch: x86

      - name: Install `Inetc` from web
        uses: negrutiu/nsis-install-plugin@v1
        with:
          url: https://nsis.sourceforge.io/mediawiki/images/c/c9/Inetc.zip

      - name: Build installer
        run: makensis.exe installer.nsi

      - name: Upload distributable artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: TinyWiiBackupManagerInstaller.exe

  release:
    name: Create GitHub Release
    if: github.ref_type == 'tag'
    runs-on: ubuntu-slim
    needs: [build]
    steps:
      - name: Download distributables
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/TinyWiiBackupManagerInstaller.exe
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
